# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'Jolly Chat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Jolly Chat
  # Pods for Jolly Chat iOS13
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

end
